#!/bin/sh
sleep 3
DATE=`date +%Y%m%d-%H%M%S`
HOSTNAME=`hostname` 
USERNAME=`whoami`
BUGREPORT=bugreport.$HOSTNAME.$USERNAME.$DATE.txt

echo "UnrealIRCd Bug Report" > $BUGREPORT
echo "---------------------" >> $BUGREPORT
echo "" >> $BUGREPORT
echo "Made at `date`">> $BUGREPORT
echo "`src/ircd -v`" >> $BUGREPORT
echo "Operating system:" >> $BUGREPORT
ls -l *core* >> $BUGREPORT
uname -a >> $BUGREPORT
gdb -x .bugreport.gdb src/ircd *core* >> $BUGREPORT 2>&1

exit 0

cat |sendmail -t << __EOF__&
To: bugs-unreal@tspre.org
From: autobugreport@unrealircd.com
Subject: Bug report - $BUGREPORT

`cat $BUGREPORT`

.
__EOF__
