#!/bin/sh
# This will generate a Changelog similar to our original style.
# The header before each entry is new: it contains the name of
# the author, the date, and the short hash.
# We still filter translated doc changes as to not polute the
# changelog too much.

hg log -r : --style changelog --template '[{date|shortdate}] {author} ({node|short}):\n- {desc}\n\n' \
-b unreal34 -X 'doc/unreal32docs.*.html' -X 'doc/help.*.conf' -X 'doc/example.*.conf' -X 'include/version.h'|\
sed 's/^- - /- /g' >Changes

echo "Done. File 'Changes' now contains the full version history"
