#!/bin/sh
# Rehash Script v2.0
# $Id$

IRCDPID="ircd.pid"

if [ ! -r $IRCDPID ]; then
clear
echo "**** ERROR ****"
echo "UnrealIRCd (PID: `cat $IRCDPID`) was not found running, cannot rehash"
echo ""
else
PID=`cat $IRCDPID`
kill -HUP $PID
echo "|----------------------------------------"
echo "| UnrealIRCD successfully rehashed."
echo "| Process ID: $PID"
echo "|----------------------------------------"
fi

