#!/bin/bash

# Exit on any failure:
set -e

# Verbose:
set -x

if [ "$1" != "" ]; then
	BUILDCONFIG="$1"
fi

extras/build-tests/nix/select-config $BUILDCONFIG
./Config -quick
make
make install
extras/build-tests/nix/run-tests
