#!/bin/bash

# We assume we are executed from extras/build-tests/nix

CIPHERSCAN="cipherscan"
if [ -x /home/travis/build/unrealircd/unrealircd/cipherscan/cipherscan ]; then
	CIPHERSCAN="/home/travis/build/unrealircd/unrealircd/cipherscan/cipherscan"
fi

$CIPHERSCAN --help >/dev/null || exit 1

$CIPHERSCAN --no-colors 127.0.0.1:5900|grep -vF '.....' >cipherscan.test.txt

diff -u cipherscan.expected.txt cipherscan.test.txt 1>/dev/null 2>&1
if [ "$?" -ne 0 ]; then
	echo "*** Differences found between cipherscan scan and expected output ***"
	echo "== EXPECTED OUTPUT =="
	cat cipherscan.expected.txt
	echo
	echo "== ACTUAL TEST OUTPUT =="
	cat cipherscan.test.txt
	echo
	echo "== DIFF =="
	diff -u cipherscan.expected.txt cipherscan.test.txt
	echo
	echo "cipherscan test failed."
	exit 1
fi
