// Some tight settings for a safer network

set {
    restrict-commands {
        private-message {
            except {
                security-group { trusted-user; }
                rule "tag('SENTCHANMSGS') > 15 && online_time() > 1800";
            }
        }
        private-notice {
            except {
                security-group { trusted-user; }
            }
        }
        channel-create {
            except {
                security-group { trusted-user; }
            }
        }
        channel-notice {
            except {
                security-group { trusted-user; }
            }
        }
        map {
            except {
                security-group { trusted-user; }
            }
        }
        links {
            except {
                security-group { trusted-user; }
            }
        }
        invite {
            except {
                security-group { trusted-user; }
            }
        }
        knock {
            except {
                security-group { trusted-user; }
            }
        }
        away {
            except {
                security-group { trusted-user; }
            }
        }
        module {
            except {
                security-group { trusted-user; }
            }
        }
        module {
            except {
                security-group { trusted-user; }
            }
        }
        list {
            except {
                connect-time 120;
            }
        }
        /* Only useful when using ObbyIRCd */
        register {
            except {
                rule "reputation() > 10 || online_time() > 1800 || !in_security_group('tls-or-local')";
            }
        }
        identify {
            except {
                rule "reputation() > 10 || online_time() > 1800 || !in_security_group('tls-or-local')";
            }
        }
    }
}

/*  Our trusted-user must either:
 *  1) Have a reputation of at least x with an account
 *  OR
 *  2) Have a reputation of at least 2*x with no account
*/
security-group trusted-user {
    rule "(is_identified() && reputation() > 9) || (!is_identified() && reputation() > 19) && is_tls()";
}

/* Kind of the same as above but inverted */
security-group untrusted-user {
    rule "(is_identified() && reputation() < 10) || (!is_identified() && reputation() < 20) || !is_tls()";
}

/* For making sure people use auth commands over secure connections */
security-group tls-or-local {
    rule "is_tls() || match_ip('192.168.0.0/16') || match_ip('127.0.0.0/8')";
}


/* We'll count the users channel messages as a sneaky way to
 * force them to talk to someone in an existing channel before
 * getting round our messaging restrictions
*/
spamfilter {
    target { channel; }
    rule "in_security_group('untrusted-user') && in_channel('#*')";
    action { set SENTCHANMSGS++; }
}

/* Special 'set' block just for our untrusted-users (restrict them some more)*/
set untrusted-user {
    maxchannelsperuser 3;
    /* 'restrict-usermodes' can be used to stop untrusted-users being able to advertise malicious/phishing hosts,
     * it also helps prevent vhost flooding (always use cloaks unless you're trusted!)
    */
    restrict-usermodes 'xB';
    static-quit "Leaving"; // should avoid most spammy quit msgs
    static-part "Leaving"; // should avoid most spammy part msgs
}

/* Flood restrictions to impose on untrusted-users */
set {
    anti-flood {
        untrusted-user {
            target-flood {
                channel-privmsg 5:5;
            }
            nick-flood 1:60;
            lag-penalty 1000;
            lag-penalty-bytes 50;
        }
    }
}
