<html>

	<head>
		<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
		<title>
$ TITLE
      </title>
		<style type="text/css" media="screen"> 
BODY { 
    scrollbar-base-color : Black; 
    scrollbar-3d-light-color : #D3D3D3; 
    scrollbar-dark-shadow-color : #D3D3D3; 
    scrollbar-shadow-color : #D3D3D3; 
    scrollbar-highlight-color : #D3D3D3; 
    scrollbar-arrow-color : Black; 
    scrollbar-face-color : #D3D3D3; 
    background-color : #FFFFFF; 
    font-size : 8pt; 
    font-family : "Trebuchet MS", Arial, Tahoma; 
}

.text, INPUT { 
    font-family : "Trebuchet MS", Arial, Tahoma; 
    font-size : 12px; 
} 
.status { 
    font-family : "Trebuchet MS", Arial, Tahoma; 
    font-size : 10px; 
} 
.title { 
    font-family : "Trebuchet MS", Arial, Tahoma; 
    font-size : 15pt; 
} 

.button { 
    font-family : Tahoma; 
    border : 1px solid #C8C8C8; 
    font-size : 11px; 
    cursor : hand; 
    background-color : #E5E5E5; 
}
#background { position: absolute; z-index: 0; top: 0px; left: 0px; width: 650px; height: 450px; visibility: visible }
#content           { position: absolute; top: 77px; left: 133px; width: 399px; height: 283px; visibility: visible }
#unrealIRCdLink      { font-size: 8pt; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; top: 432px; left: 0px; width: 650px; height: 16px; visibility: visible;  }
#icon { z-index: 1; font-size: 8pt; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; top: 13px; left: 22px; width: 72px; height: 73px; visibility: visible; scrollbar-3d-light-color: #D3D3D3; scrollbar-arrow-color: Black; scrollbar-base-color: Black; scrollbar-dark-shadow-color: #D3D3D3; scrollbar-face-color: #D3D3D3; scrollbar-highlight-color: #D3D3D3; scrollbar-shadow-color: #D3D3D3 }

#button1img  { z-index: 3; position: absolute; top: 150px; left: 11px; width: 111px; height: 23px; }
#button1text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 150px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button1bg   { z-index: 1; position: absolute; top: 150px; left: 11px; width: 111px; height: 23px; }
	
#button2img  { z-index: 3; position: absolute; top: 180px; left: 11px; width: 111px; height: 23px; }
#button2text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 180px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button2bg   { z-index: 1; position: absolute; top: 180px; left: 11px; width: 111px; height: 23px; }

#button3img  { z-index: 3; position: absolute; top: 210px; left: 11px; width: 111px; height: 23px; }
#button3text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 210px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button3bg   { z-index: 1; position: absolute; top: 210px; left: 11px; width: 111px; height: 23px; }

#button4img  { z-index: 3; position: absolute; top: 240px; left: 11px; width: 111px; height: 23px; }
#button4text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 240px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button4bg   { z-index: 1; position: absolute; top: 240px; left: 11px; width: 111px; height: 23px; }

#button5img  { z-index: 3; position: absolute; top: 270px; left: 11px; width: 111px; height: 23px; }
#button5text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 270px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button5bg   { z-index: 1; position: absolute; top: 270px; left: 11px; width: 111px; height: 23px; }

#button6img  { z-index: 3; position: absolute; top: 300px; left: 11px; width: 111px; height: 23px; }
#button6text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 300px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button6bg   { z-index: 1; position: absolute; top: 300px; left: 11px; width: 111px; height: 23px; }


#button7img  { z-index: 3; position: absolute; top: 330px; left: 11px; width: 111px; height: 23px; }
#button7text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 330px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button7bg   { z-index: 1; position: absolute; top: 330px; left: 11px; width: 111px; height: 23px; }


#button8img  { z-index: 3; position: absolute; top: 360px; left: 11px; width: 111px; height: 23px; }
#button8text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 360px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button8bg   { z-index: 1; position: absolute; top: 360px; left: 11px; width: 111px; height: 23px; }

#button9img  { z-index: 3; position: absolute; top: 390px; left: 11px; width: 111px; height: 23px; }
#button9text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 390px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button9bg   { z-index: 1; position: absolute; top: 390px; left: 11px; width: 111px; height: 23px; }

#button10img  { z-index: 3; position: absolute; top: 420px; left: 11px; width: 111px; height: 23px; }
#button10text { font-size: 10px; font-family: "Trebuchet MS", Arial, Tahoma; position: absolute; z-index: 2; top: 420px; left: 11px; width: 111px; height: 23px; padding: 1px}
#button10bg   { z-index: 1; position: absolute; top: 420px; left: 11px; width: 111px; height: 23px; }


</style>
	</head>

	<body bgcolor="#ffffff" text="black" link="black" vlink="black" alink="black">
		<div id="button1img"><a href="http://www.unrealircd.org" onMouseOver="document.button1.src='../sections/active.gif';" onMouseOut="document.button1.src='../sections/inactive.gif';"><img src="../sections/inactive.gif" name="button1" border="0"></a></div>
		<div id="button1text" align="center"><center>Operators</center></div>
		<div id="button1bg"><img src="../sections/bg.gif" border="0"></div>

		<div id="button2img"><a href="http://www.unrealircd.org" onMouseOver="document.button2.src='../sections/active.gif';" onMouseOut="document.button2.src='../sections/inactive.gif';"><img src="../sections/inactive.gif" name="button2" border="0"></a></div>
		<div id="button2text" align="center"><center>Other stuff</center></div>
		<div id="button2bg"><img src="../sections/bg.gif" border="0"></div>

		<div id="icon"><img 
$ ICON
                           width="72" height="73" border="0"></div>
		<div id="background"><img src="../back/background.jpg" width="650" border="0"></div>
		<div id="unrealIRCdLink">
		<table width="650" height="18" border="0" cellpadding="0" cellspacing="0">
		<tr><td colspan="3"><img src="../back/line.gif" width="650"></td></tr>
		<tr width="650"><td valign="middle" align="right" height="9" width="97"><a target="_blank" href="http://www.unrealircd.com/" onMouseOver="document.unreallink.src='../unrealircd.com/active.gif';" onMouseOut="document.unreallink.src='../unrealircd.com/inactive.gif';"><img src="../unrealircd.com/inactive.gif" name="unreallink" border="0"></a></td>
$ STATUSLINE

		
		
		</div>
		<div id="content">
			<div align="left"><i><span class="title">
$ SECTION
                              </span></i></div>
			<center><table border="0" cellpadding="20" cellspacing="0" width="470" height="250" borderColorDark="black" borderColorLight="black"><tr><td valign="top" borderColorDark="#ffffff" borderColorLight="#ffffff">
$ DATA
			</td></tr></table></center>
		</div>
	</body>
</html>