#!/bin/sh
MAKE="$1"
echo ""
echo "Checking for updates for third party modules..."
# We can't use the "unrealircd" script, since possibly the ircd
# has not been installed to it's final location.. yet.
# So this is basically "unrealircd module upgrade --no-install":
../../ircd -m upgrade --no-install
echo ""
echo "Building all third party modules..."
for x in *.c
do
if [ "$x" != "*.c" ]; then
	x="`echo $x|sed 's/\.c//'`"
	# Always rebuild, because we can't detect include/*.h changes
	# and this would cause 3rd party modules not to be built.
	# See https://bugs.unrealircd.org/view.php?id=6365
	# Also, this deletes the .so file explicitly, so if the
	# make custommodule command fails, unrealircd does not use the
	# old .so file, which would be bad.
	rm -f $x.so
	echo "Building 3rd party module $x..."
	$MAKE custommodule MODULEFILE=$x || (echo "*****"; echo "Building 3rd party module $x failed."; echo "Contact the module author of the $x module (not the UnrealIRCd team), or simply delete the $PWD/$x.c file"; echo "*****")
fi
done
